### ISSUE TITLE
Arduino ST7789 lib not working with 320x240 Display

### ISSUE THREAD

**Issue by Boregard** [Wiz-IO/wizio-pico-examples#4]
The arduino [pico-tft-dma-st7789](https://github.com/Wiz-IO/wizio-pico-examples/tree/main/arduino/pico-tft-dma-st7789) library is not working with displays with width of 320 pixels (like [this one](https://www.berrybase.de/raspberry-pi/raspberry-pi-mikrocontroller/erweiterungsboards/2-zoll-lcd-display-modul-f-252-r-raspberry-pi-pico-65k-farben-320-215-240-spi)).
Reason is an overflow of `uint8_t` in:
  `uint8_t _colstart, _rowstart, _xstart, _ystart;`
in ST7789.h
and an overflow in hal_tft where `uint16_t` is too small for size parameter:
    `void tft_spi_put_data(uint16_t data, uint16_t size, int bits);`
    `void tft_spi_put_buffer(uint16_t *buffer, uint16_t size, int bits);`
which should be `uint` instead.

**Comment by Wiz-IO** [comment]
tested with ILI9341 
https://www.youtube.com/watch?v=Lolq46mt-vY

**Comment by Boregard** [comment]
Right, my bad, the issue is only in hal_tft code. Will open separate issue.
